apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-deployment
  labels:
    app:  my-deployment
spec:
  selector:
    matchLabels:
      app: my-deployment
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  my-deployment
    spec:
      containers:
      - name:  my-deployment
        image:  nginx:1.16.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  my-deployment
      restartPolicy: Always