apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-aula
  labels:
    app:  nginx-aula
spec:
  selector:
    matchLabels:
      app: nginx-aula
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx-aula
    spec:
      containers:
      - name:  nginx-aula
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always