apiVersion: apps/v1
kind: Deployment
metadata:
  name:  meu-app-node
  labels:
    app:  meu-app-node
spec:
  selector:
    matchLabels:
      app: meu-app-node
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  meu-app-node
    spec:
      containers:
      - name:  meu-app-node
        image:  vitorferreir/meu-app-node:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  meu-app-node
      restartPolicy: Always