apiVersion: v1
kind: Service
metadata:
  name: meu-app-node
  namespace: default
spec:
  selector:
    app: meu-app-node
  type: NodePort
  ports:
  - name: meu-app-node
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000